### ISSUE TITLE
MacOS root user is not able to use Twingate

### ISSUE THREAD

**Issue by muhamedkarajic** [Twingate/pulumi-twingate#50]
I have been using your application twingate for MacOS which I download over the AppStore. It works fine on the user account. However when I try to use twingate as the Root user using the root login on MacOS it fails.

I have troubleshooted the issue and this is the error:
```
2024-04-20 20:52:15.744+0200 [ERROR] [client] Unable to evaluate DeviceOwnerAuthenticationWithBiometrics policy, code: -8, exception: Biometry is locked out.
2024-04-20 20:52:15.803+0200 [ERROR] [client] -[VPNManager finishStartWithError:] [Line 374] Start finished with error Error Domain=com.anchorfree.hydra.manager Code=4 "failed_to_connect" UserInfo={NSLocalizedDescription=failed_to_connect}
2024-04-20 20:52:15.803+0200 [ERROR] [client] Connect failed: failed_to_connect
```

While digging into it deeper the error is all about the fact that twingate checks the biometry and if its locked out it dose not allow the connection to the network. While this is ok for most cases in the case of the root user the biometry is always locked out cause biometry is not needed.

Hope someone can reach out and offer a fix for this.

**Comment by alexb-twingate** [comment]
Hi @muhamedkarajic, we'll look into this issue!

I went ahead and installed Twingate on a VM as the Root user and I was able to sign in to a Network. Try ensuring that the Twingate VPN profile is installed and enabled (you may need to enable it as another user). I suspect this may be an issue due the error coming from `VPNManager`.

The biometrics error you see should be unrelated. We handle that specific error and log it in case someone needs to debug why [the biometric posture check](https://www.twingate.com/docs/device-posture-checks#macos) is failing. Further, in my case, biometrics weren't locked out on root, just disabled.

In the meantime, I'm going to close this issue as this is the repo for our Pulumi provider and not the appropriate place for technical help. Feel free to reach out for support via [the Twingate Help Center](help.twingate.com) or via [the Twingate community forum](https://reddit.com/r/twingate).

**Comment by muhamedkarajic** [comment]
@alexb-twingate what dose exactly mean:
> Try ensuring that the Twingate VPN profile is installed and enabled (you may need to enable it as another user). I suspect this may be an issue due the error coming from VPNManager.

I have trouble understading what you are saying, I enabled root (username) and logged in as him, and I get those errors.

**Comment by alexb-twingate** [comment]
To check whether the Twingate VPN profile is installed, navigate to System Settings > VPN. See whether an entry exists for Twingate.

<img width="708" alt="Screenshot 2024-05-06 at 12 03 02" src="https://github.com/Twingate/pulumi-twingate/assets/110070580/fb24d778-57bd-4bc5-802f-6891857a2675">

To enable the VPN profile:
- Run Twingate. During onboarding you should see whether or not the profile is enabled. If onboarding doesn't display, the profile should be enabled.
  - You may need to do this as a user who isn't root. The macOS root user may not be able to do this; this is a macOS limitation and not a Twingate limitation.

If you need more support, you should engage us via [the Twingate Help Center](https://github.com/Twingate/pulumi-twingate/issues/help.twingate.com) or via [the Twingate community forum](https://reddit.com/r/twingate). This is not a forum for technical support with the Twingate client.
