### ISSUE TITLE
Issues when trying to use the provider in golang

### ISSUE THREAD

**Issue by victorlcm** [Twingate/pulumi-twingate#90]
Hi,

I'm getting the error `go: module github.com/Twingate/pulumi-twingate@upgrade found (v3.0.4+incompatible), but does not contain package github.com/Twingate/pulumi-twingate/sdk/go/twingate` when trying to install the provider in my Pulumi project using the golang sdk. Can someone help with this?

Thanks!

**Comment by twingate-blee** [comment]
I was not able to reproduce the issue. Does the example at https://github.com/Twingate/pulumi-twingate/tree/main/examples/go work for you?

**Comment by knmsk** [comment]
Same error here, I've tried to get the package using `go get github.com/Twingate/pulumi-twingate/sdk/v3` but the output is `module github.com/Twingate/pulumi-twingate@upgrade found (v3.0.6+incompatible), but does not contain package github.com/Twingate/pulumi-twingate/sdk`.

The steps to reproduce the error in my case:
1. Clone https://github.com/pulumi/pulumi-component-provider-go-boilerplate (component builder for golang)
2. Update the go.mod file with Golang version 1.22 or others manually editing the file or running `go mod edit -go=1.22`
3. Run `go mod tidy`
4. Run `go get github.com/Twingate/pulumi-twingate/sdk/v3`

**Comment by twingate-blee** [comment]
I was able to reproduce the issue when I ran the example outside of the repo. Here is a PR with the updated example https://github.com/Twingate/pulumi-twingate/pull/109
